/** VAT % on net merchandise after discounts (UAE). Use `taxRateDefault: 0` in pricing options for exemptions. */
export const ORDER_VAT_PERCENT = 5;

export const ORDER_STATUS = {
  DRAFT: 'draft',
  PENDING: 'pending',
  CONFIRMED: 'confirmed',
  INVOICED: 'invoiced',
  PROCESSING: 'processing',
  PACKED: 'packed',
  PICKED: 'picked',
  READY_TO_DELIVER: 'ready_to_deliver',
  READY_TO_SHIP: 'ready_to_ship',
  OUT_FOR_DELIVERY: 'out_for_delivery',
  SHIPPED: 'shipped',
  DELIVERED: 'delivered',
  CANCELLED: 'cancelled',
  RETURNED: 'returned',
  PARTIALLY_RETURNED: 'partially_returned',
} as const;

export const STATUS_TRANSITIONS: Record<string, string[]> = {
  draft: ['pending', 'cancelled'],
  pending: ['confirmed', 'cancelled'],
  confirmed: ['invoiced', 'cancelled'],
  invoiced: ['processing', 'picked', 'cancelled'],
  processing: ['picked', 'cancelled'],
  picked: ['packed', 'cancelled'],
  packed: ['ready_to_deliver', 'ready_to_ship', 'cancelled'],
  ready_to_deliver: ['ready_to_ship', 'out_for_delivery', 'cancelled'],
  ready_to_ship: ['out_for_delivery', 'shipped', 'cancelled'],
  out_for_delivery: ['shipped', 'delivered', 'cancelled'],
  shipped: ['delivered', 'cancelled'],
  delivered: ['returned', 'partially_returned'],
  cancelled: [],
  returned: [],
  partially_returned: ['returned', 'partially_returned'],
};

export const USER_ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  MANAGER: 'manager',
  SALES: 'sales',
  WAREHOUSE: 'warehouse',
  DELIVERY: 'delivery',
  ACCOUNTANT: 'accountant',
  VIEWER: 'viewer',
  HR_MANAGER: 'hr_manager',
  PAYROLL_OFFICER: 'payroll_officer',
} as const;

export const MODULES = [
  'dashboard',
  'products',
  'categories',
  'inventory',
  'orders',
  'customers',
  'payments',
  'reports',
  'users',
  'roles',
  'settings',
  'attendance',
  'leave',
  'shop_visits',
  // Payroll modules
  'employees',
  'paycycles',
  'advances',
  'earning_deductions',
  'payroll_runs',
  'payroll_archives',
  'lookup_values',
  'adhoc_items',
  'holidays',
] as const;

export const ACTIONS = [
  'create',
  'read',
  'update',
  'delete',
  'export',
  'import',
  'approve',
  'manage_credit',
  'view_financial',
  'manage_inventory',
  'process_payment',
  'change_status',
  // Payroll actions
  'calculate',
  'finalize',
  'generate_payslip',
  'disburse',
] as const;

export const ROLE_PERMISSIONS: Record<string, any> = {
  super_admin: '*',
  admin: {
    dashboard: ['read'],
    products: ['create', 'read', 'update', 'delete', 'import', 'export'],
    categories: ['create', 'read', 'update', 'delete'],
    inventory: ['read', 'update', 'manage_inventory'],
    orders: ['create', 'read', 'update', 'change_status', 'export'],
    customers: ['create', 'read', 'update', 'delete', 'manage_credit', 'view_financial'],
    payments: ['create', 'read', 'process_payment'],
    reports: ['read', 'export'],
    users: ['create', 'read', 'update'],
    settings: ['read', 'update'],
    attendance: ['create', 'read', 'update', 'delete', 'approve'],
    leave: ['create', 'read', 'update', 'delete', 'approve'],
    shop_visits: ['create', 'read', 'update', 'delete'],
    // Payroll permissions (admin has all)
    employees: ['create', 'read', 'update', 'delete', 'import', 'export'],
    paycycles: ['create', 'read', 'update', 'delete'],
    advances: ['create', 'read', 'update', 'approve', 'disburse'],
    earning_deductions: ['create', 'read', 'update', 'delete'],
    payroll_runs: ['create', 'read', 'update', 'calculate', 'approve', 'finalize', 'generate_payslip'],
    payroll_archives: ['read', 'export'],
    lookup_values: ['create', 'read', 'update', 'delete'],
    adhoc_items: ['create', 'read', 'update', 'delete', 'approve'],
    holidays: ['create', 'read', 'update', 'delete'],
  },
  manager: {
    dashboard: ['read'],
    products: ['create', 'read', 'update'],
    categories: ['read'],
    inventory: ['read', 'update'],
    orders: ['create', 'read', 'update', 'change_status'],
    customers: ['create', 'read', 'update', 'view_financial'],
    payments: ['read', 'process_payment'],
    reports: ['read'],
    attendance: ['create', 'read', 'update', 'approve'],
    leave: ['create', 'read', 'update', 'approve'],
    shop_visits: ['create', 'read', 'update'],
    // Limited payroll access
    employees: ['read'],
    advances: ['read', 'approve'],
    payroll_runs: ['read'],
    payroll_archives: ['read'],
    adhoc_items: ['read', 'approve'],
  },
  sales: {
    dashboard: ['read'],
    products: ['read'],
    orders: ['create', 'read', 'update'],
    customers: ['create', 'read', 'update'],
    payments: ['read'],
    attendance: ['create', 'read'],
    leave: ['create', 'read'],
    shop_visits: ['create', 'read'],
    // Self-service payroll access
    employees: ['read'],
    advances: ['create', 'read'],
    payroll_archives: ['read'],
  },
  warehouse: {
    dashboard: ['read'],
    products: ['read'],
    inventory: ['read', 'update', 'manage_inventory'],
    orders: ['read', 'change_status'],
    attendance: ['create', 'read'],
    leave: ['create', 'read'],
    // Self-service payroll access
    employees: ['read'],
    advances: ['create', 'read'],
    payroll_archives: ['read'],
  },
  delivery: {
    orders: ['read', 'change_status'],
    customers: ['read'],
    attendance: ['create', 'read'],
    leave: ['create', 'read'],
    shop_visits: ['create', 'read'],
    // Self-service payroll access
    employees: ['read'],
    advances: ['create', 'read'],
    payroll_archives: ['read'],
  },
  accountant: {
    dashboard: ['read'],
    orders: ['read'],
    customers: ['read', 'view_financial', 'manage_credit'],
    payments: ['create', 'read', 'process_payment'],
    reports: ['read', 'export'],
    attendance: ['read'],
    leave: ['read'],
    // Payroll access for accountant
    employees: ['read'],
    payroll_runs: ['read', 'approve'],
    payroll_archives: ['read', 'export'],
    advances: ['read'],
  },
  viewer: {
    dashboard: ['read'],
    products: ['read'],
    orders: ['read'],
    customers: ['read'],
    reports: ['read'],
    attendance: ['read'],
    leave: ['read'],
  },
  // New HR Manager role
  hr_manager: {
    dashboard: ['read'],
    attendance: ['create', 'read', 'update', 'approve'],
    leave: ['create', 'read', 'update', 'approve'],
    employees: ['create', 'read', 'update', 'import', 'export'],
    paycycles: ['read'],
    advances: ['create', 'read', 'update', 'approve'],
    earning_deductions: ['read'],
    payroll_runs: ['create', 'read', 'calculate'],
    payroll_archives: ['read'],
    lookup_values: ['read'],
    users: ['read'],
    adhoc_items: ['create', 'read', 'update', 'approve'],
    holidays: ['create', 'read', 'update', 'delete'],
  },
  // New Payroll Officer role
  payroll_officer: {
    dashboard: ['read'],
    attendance: ['read'],
    leave: ['read'],
    employees: ['read'],
    paycycles: ['read'],
    advances: ['read', 'approve', 'disburse'],
    earning_deductions: ['read'],
    payroll_runs: ['create', 'read', 'update', 'calculate', 'generate_payslip'],
    payroll_archives: ['read'],
    lookup_values: ['read'],
    adhoc_items: ['create', 'read', 'update', 'approve'],
    holidays: ['read'],
  },
};

export const INVENTORY_TRANSACTION_TYPES = {
  PURCHASE: 'purchase',
  SALE: 'sale',
  ADJUSTMENT: 'adjustment',
  RETURN: 'return',
  PURCHASE_RETURN: 'purchase_return',
  TRANSFER: 'transfer',
  DAMAGE: 'damage',
} as const;

export const DEFAULT_PAGINATION = {
  PAGE: 1,
  LIMIT: 20,
  MAX_LIMIT: 100,
} as const;
